CREATE EVENT SESSION [XE_REBUILD_ONLINE] ON SERVER 
ADD EVENT sqlserver.progress_report_online_index_operation(
    ACTION(sqlos.task_time,sqlserver.database_name)) 
ADD TARGET package0.ring_buffer(SET max_memory=(4096000))
WITH (MAX_MEMORY=4096 KB,EVENT_RETENTION_MODE=ALLOW_SINGLE_EVENT_LOSS,MAX_DISPATCH_LATENCY=30 SECONDS,MAX_EVENT_SIZE=0 KB,MEMORY_PARTITION_MODE=NONE,TRACK_CAUSALITY=OFF,STARTUP_STATE=OFF)
GO


